### PR TITLE
Search posts

### LINKED ISSUE #50: search

### PR DESCRIPTION
**Pull request by marcjulian**
close #50 

- [ ] GitHub logo visibility in light theme
- [x] Keyboard Up Down Navigation of Results
- [ ] tooltip, shortcut hint?
- [ ] result grouping,sorting,prio

### CODE REVIEW

**Comment by garygrossgarten** [comment]
I'd suggest to change the shortcut to use ctrl+s

**Comment by garygrossgarten** [comment]
I like it👏

**Comment by marcjulian** [comment]
Change search from cmd + k to ctrl + s? Yes sounds good! Or ctrl + f(ind)

**Comment by garygrossgarten** [comment]
> Change search from cmd + k to ctrl + s? Yes sounds good! Or ctrl + f(ind)

Even better. How about "Type to Search" instead of "Search"?

**Pull request merged**
