### PR TITLE
feature/angular update

### PR DESCRIPTION
**Pull request by marcjulian**
- update angular
- cleanup tailwind integration
- update scully
- enable inline fonts and inline critical styles

### CODE REVIEW

**Comment by marcjulian** [comment]
@garygrossgarten small performance boost 🚀

**Comment by garygrossgarten** [comment]
Fouc still needed with Font and style inlining?

**Comment by marcjulian** [comment]
Yes still needed, as the content of the featured post loads slower and the latest articles are pushed down otherwise.

**Comment by garygrossgarten** [comment]
What happens after running scully twice?

**Comment by marcjulian** [comment]
Same behavior

**Comment by marcjulian** [comment]
Can this be merged?

**Review by garygrossgarten — APPROVED** [review]

**Pull request merged**
