### PR TITLE
feature/tailwind 2

### PR DESCRIPTION
**Pull request by marcjulian**
- simplify purge rules and optin to future changes
- update tailwind 2.0
- use theme() function for colors
- update theme and add new primary color

### CODE REVIEW

**Comment by marcjulian** [comment]
@garygrossgarten in Tailwind 2.0 new Gray colors are introduced. We should decide which we like to use, as we use gray for the background in our themes.

We should consider downloading and serving our font ourself to improve performance as [cross-site caching](https://dev.to/zwacky/time-to-say-goodbye-to-google-fonts-16dd) is changing. We are currently using [Muli](https://fonts.googleapis.com/css?family=Muli&display=swap) We can still downloaded through this link, but it seems that I can not find Muli on https://fonts.google.com/specimen/Muli anymore.

**Comment by marcjulian** [comment]
Do we want to use [tailwindcss-typography](https://github.com/tailwindlabs/tailwindcss-typography) for the content and customize it to our design?

**Comment by garygrossgarten** [comment]
@marcjulian try it out and see what it looks like

**Comment by garygrossgarten** [comment]
@marcjulian what's missing? need this for my latest post

**Comment by marcjulian** [comment]
@garygrossgarten a few styles such as `blockquote` need some more styling in `prose` and I am going to add the gray background color we are currently using.

**Review by garygrossgarten — APPROVED** [review]
LGTM!

**Comment by marcjulian** [comment]
@garygrossgarten awesome! I will merge it now!

**Pull request merged**
