### PR TITLE
wip: links content feature

### PR DESCRIPTION
**Pull request by garygrossgarten**

### CODE REVIEW

**Comment by garygrossgarten** [comment]
missing:

* update all pages to use posts instead of blogPosts as source
* link preview scully plugin

**Comment by marcjulian** [comment]
@garygrossgarten is this ready?

**Comment by garygrossgarten** [comment]
Yes

**Comment by marcjulian** [comment]
@garygrossgarten added tags for css, design and tool.

How should it be?
tool or Tool
design or Design

**Comment by marcjulian** [comment]
Do we need stack icons for tool and design? I am adding one for CSS now

**Comment by garygrossgarten** [comment]
Yes please, Design and DevTool?

**Comment by garygrossgarten** [comment]
> Do we need stack icons for tool and design? I am adding one for CSS now

yes would be great, maybe a font awesome or ionicons svg

**Comment by marcjulian** [comment]
Okay tag `tool` is named DevTool now

**Comment by marcjulian** [comment]
Icon ideas for Design:
https://fontawesome.com/icons/palette?style=solid
https://fontawesome.com/icons/paint-brush?style=solid
https://fontawesome.com/icons/magic?style=solid

Icon idea for DevTool:
https://fontawesome.com/icons/laptop-code?style=solid

**Pull request merged**
