### PR TITLE
New tabs layout

### PR DESCRIPTION
**Pull request by marcjulian**

### CODE REVIEW

**Comment by garygrossgarten** [comment]
Could you add notiz title label to first tab?
Also i noticed that the main element has a max width. The layout change causes a cut off of the card stack. 

before:
Screenshot 2020-04-26 at 17 50 54
after:
Screenshot 2020-04-26 at 17 50 45

**Comment by marcjulian** [comment]
@garygrossgarten notiz added to the tab bar removed max-width from main. Ready to review!

**Comment by marcjulian** [comment]
@garygrossgarten I also update the background and tabs color for light mode.

**Comment by garygrossgarten** [comment]
Screenshot 2020-04-30 at 17 39 18

**Comment by garygrossgarten** [comment]
firebase logo size looks off, scully and tailwind logos are not in correct color

**Comment by garygrossgarten** [comment]
tooltips for tabs missing

**Comment by garygrossgarten** [comment]
footer text missing text-align justify

**Comment by garygrossgarten** [comment]
Screenshot 2020-04-30 at 17 48 37
 gap because of main padding

**Comment by marcjulian** [comment]
> firebase logo size looks off, scully and tailwind logos are not in correct color

Thats weird. Looks like our gradient is applied here. Maybe its because of the inline-svg.

**Comment by marcjulian** [comment]
I have no clue why the color changes for tailwind and scully svg.

**Comment by marcjulian** [comment]
Screenshot 2020-04-30 at 19 22 55

Main without padding

**Comment by garygrossgarten** [comment]
I'll have a look later

**Pull request merged**
